spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: lizichen
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.126.136
    port: 5672
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 192.168.126.136
    database: 0
    port: 6379
    password: lizichen
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.126.135:8888/
